- name: 'Direct Routing'
  tunnel: 'disabled'
  encryption: 'disabled'
  family: 'dual'
  endpoint-routes: 'enabled'
- name: 'Tunnel Mode'
  tunnel: 'vxlan'
  encryption: 'disabled'
  family: 'dual'
  endpoint-routes: 'enabled'
- name: 'Direct Routing with Local Node Routes'
  tunnel: 'disabled'
  encryption: 'disabled'
  family: 'dual'
  endpoint-routes: 'disabled'
- name: 'Tunnel Mode with Local Node Routes'
  tunnel: 'vxlan'
  encryption: 'disabled'
  family: 'dual'
  endpoint-routes: 'disabled'
- name: 'Direct Routing with KVStore'
  tunnel: 'disabled'
  encryption: 'disabled'
  family: 'dual'
  kvstore: 'true'
  endpoint-routes: 'enabled'
- name: 'Tunnel Mode with KVStore'
  tunnel: 'vxlan'
  encryption: 'disabled'
  family: 'dual'
  kvstore: 'true'
  endpoint-routes: 'enabled'
- name: 'Direct Routing with IPSec Encryption'
  tunnel: 'disabled'
  encryption: 'ipsec'
  family: 'dual'
  endpoint-routes: 'enabled'
- name: 'Tunnel Mode with IPSec Encryption'
  tunnel: 'vxlan'
  encryption: 'ipsec'
  family: 'dual'
  endpoint-routes: 'enabled'
- name: 'Direct Routing with WireGuard Encryption'
  tunnel: 'disabled'
  encryption: 'wireguard'
  family: 'dual'
  endpoint-routes: 'enabled'
- name: 'Tunnel Mode with WireGuard Encryption'
  tunnel: 'vxlan'
  encryption: 'wireguard'
  family: 'dual'
  endpoint-routes: 'enabled'
